# Generated by Django 4.0.3 on 2022-04-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hours_worked',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
