# Generated by Django 4.0.3 on 2022-04-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='screen_shot',
            field=models.ImageField(default='default.jpg', upload_to='screen_shots'),
        ),
    ]
